(()=>{
  const link=document.createElement('link');link.rel='stylesheet';link.href='/product-demo.css';document.head.appendChild(link);
  if(document.getElementById('ee-product-explorer'))return;
  const product=document.querySelector('#product');if(!product)return;
  const section=document.createElement('section');section.id='ee-product-explorer';section.className='pdx-demo-section';
  section.innerHTML=`<div class="shell pdx-demo-wrap">
    <div class="pdx-head"><div><span class="pdx-kicker" data-demo-en="OFFICIAL-SOURCE PROPERTY EXPLORER" data-demo-et="AMETLIKU ALLIKA KINNISVARA EXPLORER">OFFICIAL-SOURCE PROPERTY EXPLORER</span><h2 data-demo-en="One cadastral identity. The property systems behind it, connected." data-demo-et="Üks katastriidentiteet. Selle taga olevad kinnisvarasüsteemid, ühendatud.">One cadastral identity. The property systems behind it, connected.</h2><p data-demo-en="Use the documented Pärnu mnt 51a example to inspect how cadastral land, official assessed value, EHR building specifications, energy history and documents land in one source-aware response without pretending restricted land-register rights are open data." data-demo-et="Vaata dokumenteeritud Pärnu mnt 51a näite kaudu, kuidas katastrimaa, ametlik maa hinnatud väärtus, EHR hooneandmed, energiaajalugu ja dokumendid jõuavad ühte allikateadlikku vastusesse, ilma et piiratud kinnistusraamatu õigusi esitletaks avaandmetena.">Use the documented Pärnu mnt 51a example to inspect how cadastral land, official assessed value, EHR building specifications, energy history and documents land in one source-aware response without pretending restricted land-register rights are open data.</p></div><div class="pdx-head-actions"><a class="pdx-btn primary" href="/workspace" data-demo-en="Open Estonia Workspace →" data-demo-et="Ava Eesti töölaud →">Open Estonia Workspace →</a><a class="pdx-btn" href="/docs" data-demo-en="Read API docs" data-demo-et="Loe API dokumente">Read API docs</a></div></div>
    <div class="pdx-browser" aria-label="PropData Estonia property response explorer">
      <div class="pdx-top"><div class="pdx-brand"><span class="pdx-live-dot"></span><b>PROPDATA EE</b><small>COUNTRY RESPONSE EXPLORER</small></div><div class="pdx-controls"><span class="pdx-badge">DOCUMENTED SOURCE EXAMPLE</span><button class="pdx-toggle active" data-pdx-view="parsed">PARSED</button><button class="pdx-toggle" data-pdx-view="json">JSON</button></div></div>
      <div class="pdx-tabs"><button class="active" data-pdx-route="property"><span>PROPERTY</span><small>identity + coverage</small></button><button data-pdx-route="land"><span>CADASTRE</span><small>official land facts</small></button><button data-pdx-route="building"><span>BUILDING</span><small>EHR specifications</small></button><button data-pdx-route="documents"><span>DOCUMENTS</span><small>energy + history</small></button></div>
      <div class="pdx-request"><span class="pdx-method">GET</span><div class="pdx-url">/v1/property?country=EE&amp;parcel=<strong>78404:406:4330</strong></div><span class="pdx-status"><i></i>DOCUMENTED · LIVE_ENRICHED SHAPE</span></div>
      <div class="pdx-pane active" data-pdx-pane="parsed"><div class="pdx-grid">
        <aside class="pdx-property"><div class="pdx-photo"><div class="pdx-shape"></div><div class="pdx-pin"></div><span class="pdx-photo-label">ESTONIA · PRODUCT VISUAL · SOURCE FACTS BELOW</span></div><div class="pdx-property-body"><div class="pdx-title-row"><div><span>CADASTRAL CODE</span><h3>78404:406:4330</h3></div><b>SOURCE-NATIVE</b></div><p>Pärnu mnt 51a example · official cadastral identity stays intact while land and EHR systems enrich around it.</p><div class="pdx-facts"><div><span>Area</span><b>600 m²</b></div><div><span>Land use</span><b>ELAMUMAA 100%</b></div><div><span>Assessed land value</span><b>€123,108</b></div><div><span>EHR building</span><b>101000361</b></div></div></div></aside>
        <section class="pdx-panel"><div class="pdx-panel-head"><div><span id="pdx-route-label">PROPERTY IDENTITY + COVERAGE</span><b id="pdx-route-title">Official identity first. Enrichment only where supported.</b></div><span class="pdx-schema">SOURCE-AWARE · RIGHTS-AWARE</span></div><div class="pdx-cards" id="pdx-cards"></div><div class="pdx-sourcebar"><div><span>CADASTRE</span><b>Maa- ja Ruumiamet</b></div><div><span>BUILDINGS</span><b>Estonia Register of Construction Works (EHR)</b></div><div><span>NORMALIZATION</span><b>PropData country graph</b></div><div><span>RIGHTS BOUNDARY</span><b>RIK e-Land Register remains separate</b></div></div></section>
      </div></div>
      <div class="pdx-pane" data-pdx-pane="json"><div class="pdx-json"><div class="pdx-json-copy"><span>COUNTRY CONTRACT</span><h3>One response.<br>Multiple official systems.</h3><p>The JSON preserves cadastral identity, official land facts, EHR building detail and explicit source boundaries. Ownership category is not named-owner identity; assessed land value is not a market AVM.</p><a href="/docs">Inspect the Estonia contract →</a></div><pre id="pdx-json"></pre></div></div>
      <div class="pdx-proof"><div><b>1.39M+</b><span>official addresses</span></div><div><b>778K+</b><span>land-enriched cadastral units</span></div><div><b>971K+</b><span>building ↔ parcel links</span></div><div><b>2.44M+</b><span>property objects</span></div><div><b>10.27M+</b><span>object ↔ address links</span></div></div>
    </div>
    <div class="pdx-bottom"><div><small>WHAT THIS PROVES</small><b data-demo-en="Estonia is not a flag on a generic endpoint. The product keeps cadastral semantics, EHR building depth, official assessed value, document history, provenance and legal-access boundaries visible in one governed contract." data-demo-et="Eesti ei ole lihtsalt lipp üldise API kõrval. Toode säilitab katastrisemantika, EHR hoone sügavuse, ametliku hinnatud maa väärtuse, dokumendiajaloo, päritolu ja õigusliku ligipääsu piirid ühes hallatud lepingus.">Estonia is not a flag on a generic endpoint. The product keeps cadastral semantics, EHR building depth, official assessed value, document history, provenance and legal-access boundaries visible in one governed contract.</b></div><div class="pdx-pills"><span>Cadastral identity</span><span>€ assessed value</span><span>EHR buildings</span><span>Energy history</span><span>Documents</span><span>Provenance</span></div></div>
  </div>`;
  product.insertAdjacentElement('afterend',section);

  const data={
    property:{label:'PROPERTY IDENTITY + COVERAGE',title:'Official identity first. Enrichment only where supported.',cards:[['01','CADASTRAL CODE','78404:406:4330','Native source identifier',''],['02','GLOBAL PARCEL ID','ads_ky.10761487','Canonical PropData parcel anchor','blue'],['03','GEOMETRY','Polygon','Available parcel geometry in example','blue'],['04','AREA','600 m²','Official cadastral land area',''],['05','MATCH','cadastral_code','Source-native resolution semantics',''],['06','COVERAGE','live_enriched','Example response coverage state','blue']],json:{country_code:'EE',match_level:'cadastral_code',coverage_status:'live_enriched',parcel:{global_parcel_id:'EE:MAARUUM:CADASTRE:ads_ky.10761487',geometry:{type:'Polygon'}},source_boundary:'official facts only'}},
    land:{label:'OFFICIAL CADASTRAL LAND INTELLIGENCE',title:'Land facts stay source-native and clearly typed.',cards:[['01','AREA','600 m²','Official cadastral area',''],['02','INTENDED USE','ELAMUMAA','Residential land · 100%',''],['03','OWNERSHIP TYPE','Eraomand','Ownership category — not a named owner','gold'],['04','ASSESSED VALUE','€123,108','Official cadastral assessed land value',''],['05','IMMOVABLE NO.','3298301','Registered-immovable reference','blue'],['06','VALUATION TYPE','Official assessed','Not represented as a market AVM','gold']],json:{estonia:{land:{cadastral_code:'78404:406:4330',area_sqm:600,intended_uses:[{use:'ELAMUMAA',percent:100}],ownership_type:'Eraomand',assessed_land_value_eur:123108,registered_immovable_number:'3298301'}}}},
    building:{label:'EHR BUILDING INTELLIGENCE',title:'Physical building detail joins the parcel graph.',cards:[['01','EHR CODE','101000361','Official building identifier',''],['02','FIRST USE','1956','Recorded first-use year',''],['03','FLOORS','2','Building specification',''],['04','CLOSED NET AREA','113 m²','EHR dimension','blue'],['05','FOOTPRINT','92 m²','EHR footprint area','blue'],['06','SOURCE','EHR','Estonia Register of Construction Works','']],json:{estonia:{ehr_buildings:[{ehr_code:'101000361',first_usage_year:1956,dimensions:{floors_count:2,closed_net_area_sqm:113,footprint_area_sqm:92}}]}}},
    documents:{label:'ENERGY + DOCUMENT HISTORY',title:'A building is more than dimensions.',cards:[['01','ENERGY HISTORY','1 certificate','Available certificate history count',''],['02','DOCUMENTS','14','Available EHR document events',''],['03','PERMITS','Categorized','Permit / notice vocabulary normalized','blue'],['04','HISTORY','Source-aware','Events retain EHR context',''],['05','CURRENT RIGHTS','Separate access','Not inferred from document history','gold'],['06','NAMED OWNERS','Not implied','RIK e-Land Register boundary preserved','gold']],json:{estonia:{ehr_buildings:[{ehr_code:'101000361',energy_certificate_history:{count:1},documents:{count:14}}]},rights_boundary:{named_owners:'separate RIK e-Land Register access',current_mortgages:'not inferred from EHR history'}}}
  };
  const cards=section.querySelector('#pdx-cards'),label=section.querySelector('#pdx-route-label'),title=section.querySelector('#pdx-route-title'),json=section.querySelector('#pdx-json');
  const render=key=>{const r=data[key];label.textContent=r.label;title.textContent=r.title;cards.innerHTML=r.cards.map((c,i)=>`<article><div class="pdx-card-top"><span>${c[0]}</span><b class="pdx-state ${c[4]}">${c[4]==='gold'?'BOUNDARY':i===0?'SOURCE':'COVERED'}</b></div><small>${c[1]}</small><strong>${c[2]}</strong><p>${c[3]}</p></article>`).join('');json.textContent=JSON.stringify(r.json,null,2)};render('property');
  section.querySelectorAll('[data-pdx-route]').forEach(btn=>btn.addEventListener('click',()=>{section.querySelectorAll('[data-pdx-route]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(btn.dataset.pdxRoute)}));
  section.querySelectorAll('[data-pdx-view]').forEach(btn=>btn.addEventListener('click',()=>{section.querySelectorAll('[data-pdx-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');section.querySelectorAll('[data-pdx-pane]').forEach(p=>p.classList.toggle('active',p.dataset.pdxPane===btn.dataset.pdxView))}));
  const sync=()=>{let lang='en';try{lang=localStorage.getItem('propdata_ee_lang')==='et'?'et':(document.documentElement.lang.toLowerCase().startsWith('et')?'et':'en')}catch{}section.querySelectorAll('[data-demo-en]').forEach(el=>{const v=el.getAttribute('data-demo-'+lang);if(v)el.textContent=v})};sync();document.querySelectorAll('.lang-btn').forEach(btn=>btn.addEventListener('click',()=>setTimeout(sync,0)));
})();
